### ISSUE TITLE
Add Responsive Navbar

### ISSUE THREAD

**Issue by Buddhad** [Buddhad/contributors22#1]
- Home
- About
- Official Website
- Contact Us

**Comment by Potato-29** [comment]
Hi @Buddhad , I'd like to create this navbar :) can you assign it for me?

**Comment by Potato-29** [comment]
Hi @Buddhad , I'd like to work on this issue

**Comment by Potato-29** [comment]
Hi @Buddhad I've finished the navbar here take a look


https://user-images.githubusercontent.com/53327808/194750874-ebf5644b-ea45-47b3-9420-f511360046ab.mp4

**Comment by DHRUVKHANDELWAL00** [comment]
hey @Potato-29  please assign it to me if u want animated nav-bar too.

**Comment by Buddhad** [comment]
> Hi @Buddhad I've finished the navbar here take a look
> 
>  2022-10-09.15-38-49.mp4

Its look nice

**Comment by Divxsh** [comment]
Assign me..
