### ISSUE TITLE
Add Splash Screen Animation

### ISSUE THREAD

**Issue by Buddhad** [Buddhad/contributors22#14]

**Comment by NMN03** [comment]
hey  @Buddhad  could you please assign this issue to me
I would love to work on it

**Comment by Buddhad** [comment]
> 

Alright

**Comment by Buddhad** [comment]
> hey @Buddhad could you please assign this issue to me I would love to work on it
It's 5 days already did you complete your task or else I will unassign you?

**Comment by NMN03** [comment]
I've been trying to figure it out but I havent made much progress.
You better unassign me...
Sorry

**Comment by N-Deepika** [comment]
Can I work on this issue ?

**Comment by Buddhad** [comment]
> Can I work on this issue ?

Alright 👍
