### ISSUE TITLE
Improve dropdown 

### ISSUE THREAD

**Issue by Peacexoom** [Buddhad/contributors22#37]
In mobile and tablet screen dropdown is not properly working when we toggle on hamburger icon.

**Comment by Peacexoom** [comment]
Please assign me this issue

**Comment by Buddhad** [comment]
> Please assign me this issue

Alright

**Comment by Divxsh** [comment]
assign me.

**Comment by Buddhad** [comment]
> assign me.

Add hover effect on the dropdown.
